name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
      - name: Unit tests
        run: python test/unit/test_fire_gdp.py
      - name: Functional tests
        run: bash test/func/test_fire_gdp.sh
